#!/bin/bash

set -euo pipefail

prog='timeout -s INT 30 ./client.py'
args="--size $(( 64 * 1024 ))"
sotype=stream
threads=1
cid="2"
desc=client
while [[ "$#" -gt 0 ]]; do
	case $1 in
		-t|--threads)
			threads=$2
			shift
			shift
			;;
		-s|--server)
			cid=""
			args=""
			desc=server
			prog=./server.py
			shift
			;;
		-d|--dgram)
			sotype=dgram
			shift
			;;
	esac
done

cleanup() {
	echo "Exiting program"
	kill -s 9 $(pgrep server.py) &>/dev/null || true
	kill -s 9 $(pgrep client.py) &>/dev/null || true
}

trap cleanup EXIT SIGINT

PORT_START=100
PORT_END=$((${PORT_START} + ${threads}))
PORTS=$(seq ${PORT_START} ${PORT_END})

set -x
for port in ${PORTS};
do
	${prog} ${sotype} ${cid} ${port} ${args} &> vsock_${desc}_port${port}.log &
done

wait
